### ISSUE TITLE
Use custom name for a state machine and add waitTimeScale option

### ISSUE THREAD

**Issue by dicrescenzoa** [codetheweb/serverless-step-functions-local#18]
Source:
https://www.serverless.com/plugins/serverless-step-functions#adding-a-custom-name-for-a-statemachine

https://github.com/codetheweb/stepfunctions-localhost#startoptions

Suggestions:

https://github.com/dicrescenzoa/serverless-step-functions-local/blame/509eec077661bb0b343a7ec6d9421b65d83d7474/index.js#L79

https://github.com/dicrescenzoa/serverless-step-functions-local/blame/509eec077661bb0b343a7ec6d9421b65d83d7474/index.js#L140

My fork:
https://github.com/dicrescenzoa/serverless-step-functions-local

Thank you :)

**Comment by codetheweb** [comment]
Happy to accept a PR!

**Comment by dicrescenzoa** [comment]
Thank you! here the PR!

https://github.com/codetheweb/serverless-step-functions-local/pull/19
